---
  name: docker-builder-tags
  on:
    push:
      tags:
        - 'v*'
    repository_dispatch:
      types:
        - refresh

  jobs:
    docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          python_version:
            - 3.8
            - 3.6
            - 3.9
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Docker meta for TAG
          id: meta
          uses: docker/metadata-action@v3
          if: ${{ github.event.action != 'refresh' }}
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              type=match,pattern=v(.*),group=1, enable=true,priority=600,prefix=${{matrix.python_version}}-v,suffix=,value=

        - name: Docker meta for TAG (refresh image)
          id: meta
          uses: docker/metadata-action@v3
          if: ${{ github.event.action == 'refresh' }}
          env:
            LATEST_TAG: $(git describe --tags --abbrev=0)
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              raw=enable=true,priority=600,prefix=${{matrix.python_version}}-v,suffix=,value=${LATEST_TAG}

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ matrix.python_version }}/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
