---
  name: docker-builder-tags
  on:
    push:
      tags:
        - 'v*'
    repository_dispatch:
      types:
        - refresh

  jobs:
    docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          python_version:
            - 3.8
            - 3.6
            - 3.9
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: amd64,arm64

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Collect latest git TAG for refresh
          id: get_latest_tag
          run: |
            echo "LATEST_TAG= 0" >> $GITHUB_ENV
            echo "LATEST_TAG= $(git describe --tags --abbrev=0)" >> $GITHUB_ENV

        - name: Docker meta for TAG
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              type=match,pattern=v(.*),group=1, enable=true,priority=200,prefix=${{matrix.python_version}}-v,suffix=,value=
              raw=enable=true,priority=600,prefix=${{matrix.python_version}}-,suffix=,value=${{env.LATEST_TAG}}

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ matrix.python_version }}/Dockerfile
            platforms: linux/amd64, linux/arm64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
