---
  name: docker-builder-edge
  on:
    push:
      branches:
        - 'master'
    repository_dispatch:
      types:
        - refresh

  jobs:
    docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          python_version:
            - 3.8
            - 3.6
            - 3.9
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Docker meta for EDGE
          id: meta
          uses: docker/metadata-action@v3
          if: startsWith(github.ref, 'refs/heads/master')
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              type=edge,prefix=${{matrix.python_version}}-

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ matrix.python_version }}/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
